apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../apps/admission-webhook/upstream/overlays/cert-manager

patchesJson6902:
  - path: ../../add_label.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: deployment
