apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
   - ../../../../../apps/kfp-tekton/upstream/env/platform-agnostic
   - virtual-service.yaml

patchesStrategicMerge:
   - removesidemenu.yaml

patchesJson6902:
   - path: ../../add_label.yaml
     target:
        group: apps
        version: v1
        kind: Deployment
        name: metadata-envoy-deployment
   - path: ../../add_label.yaml
     target:
        group: apps
        version: v1
        kind: Deployment
        name: tekton-pipelineloop-controller
        namespace: tekton-pipelines
   - path: ../../add_label.yaml
     target:
        group: apps
        version: v1
        kind: Deployment
        name: tekton-pipelineloop-webhook
        namespace: tekton-pipelines
   - path: ../../add_label.yaml
     target:
        group: apps
        version: v1
        kind: Deployment
        name: tekton-pipelines-controller
        namespace: tekton-pipelines
   - path: ../../add_label.yaml
     target:
        group: apps
        version: v1
        kind: Deployment
        name: tekton-pipelines-webhook
        namespace: tekton-pipelines
