apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../../common/knative/knative-serving/overlays/gateways
- ../../../../../common/knative/knative-eventing/base
- network-attachment.yaml

